### ISSUE TITLE
Ejercicio #1 A

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea3-grupo-1#1]
Responder: ¿Qué es un sensor generador?

**Comment by MariaBelen1** [comment]
Se consideran sensores generadores aquellos que generan una señal eléctrica a partir de la magnitud que miden, sin necesidad de una alimentación eléctrica. Ofrecen una alternativa para medir muchas de las magnitudes ordinarias, sobre todo temperatura, fuerza y magnitudes afines.
