### ISSUE TITLE
Ejercicio #2 J

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea3-grupo-1#10]
Organizar el repositorio para que sean legibles las carpetas que contengan,
el orden de las mismas a seguir es el siguiente:
1) Proyecto (Simulación)
2) Hardware (Hoja de Datos de los Sensores usados - Datasheet)
3) Software (código)
4) Presentación (*.ppt – una presentación en Power Point de las etapas
del proyecto)
5) Bibliografía (Referencias)
3) Fecha

**Comment by ulisesaale** [comment]
Se arma el repositorio colocando todas las carpetas y sus respectivos README para la colocacion de cada trabajo realizado dejando organizado para sus distintas instancias.-

[Ejercicio #2 J#10]
