### ISSUE TITLE
Ejercicio #1 B

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea3-grupo-1#2]
Responder: ¿Cuáles son los tipos de sensores generadores?

**Comment by ulisesaale** [comment]
## Estos son algunos de los distintos tipos de sensores generadores :

- ### **Generadores termoeléctricos (TEG):**   
Estos sensores convierten las diferencias de temperatura en electricidad. Utilizan el efecto Seebeck para generar energía eléctrica a partir de un gradiente de temperatura entre dos materiales conductores diferentes.

- ###  **Generadores piezoeléctricos:**   
Los sensores piezoeléctricos generan electricidad cuando se aplican fuerzas físicas o presión sobre ellos. Son comunes en dispositivos como encendedores piezoeléctricos y sensores de vibración.

-  ### **Generadores fotovoltaicos:**   
Estos sensores utilizan células solares para convertir la luz solar en electricidad. Son ampliamente utilizados en paneles solares para producir energía eléctrica a partir de la radiación solar.

- ### **Generadores eólicos:**   
Los generadores eólicos convierten la energía cinética del viento en electricidad. Son comunes en parques eólicos y en sistemas de energía eólica doméstica.

- ### **Generadores hidroeléctricos:** 
Estos sensores aprovechan la energía del flujo de agua, como ríos o corrientes, para generar electricidad. Las centrales hidroeléctricas son ejemplos de generadores hidroeléctricos a gran escala.

- ### **Generadores de movimiento:** 
Algunos sensores pueden generar electricidad a partir de movimientos mecánicos, como el movimiento de una rueda giratoria o un péndulo.

- ### **Generadores de radioisótopos:**
Estos sensores utilizan la desintegración de radioisótopos para generar electricidad de manera continua. Son utilizados en aplicaciones espaciales y en dispositivos médicos implantables, como marcapasos.

- ### **Generadores termoiónicos:** 
Estos sensores generan electricidad mediante la emisión de electrones desde un cátodo caliente hacia un ánodo frío. A menudo se utilizan en aplicaciones de alto vacío.

*Es importante tener en cuenta que estos sensores generadores se utilizan en una variedad de aplicaciones, desde la generación de energía hasta la detección de movimiento y la medición de temperatura. Cada tipo de sensor generador tiene sus propias características y aplicaciones específicas en función de su principio de funcionamiento.*

**Comment by ulisesaale** [comment]
Ejercicio #1 B #2 Realizado
