### ISSUE TITLE
Ejercicio #1 C

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea3-grupo-1#3]
Responder: Mencione 5 características del sensor termopar.

**Comment by MariaBelen1** [comment]
Los termopares son dispositivos de medición de temperatura que utilizan el efecto Seebeck, que se basa en la relación entre la diferencia de temperatura y la tensión eléctrica en dos conductores diferentes. Aquí hay cinco características de los termopares:
1.	Amplio Rango de Temperatura: Los termopares pueden medir temperaturas en un rango muy amplio, desde temperaturas extremadamente bajas hasta temperaturas muy altas. Esto los hace útiles en una variedad de aplicaciones industriales y científicas.
2.	Robustez: Los termopares son dispositivos robustos y resistentes que pueden soportar condiciones adversas, como vibraciones, golpes y ambientes hostiles. Por lo tanto, son adecuados para entornos industriales exigentes.
3.	Respuesta Rápida: Los termopares tienen una respuesta rápida a los cambios de temperatura, lo que los hace útiles para la medición de procesos dinámicos.
4.	Buena Precisión: Los termopares pueden proporcionar mediciones precisas de temperatura si se calibran adecuadamente. Sin embargo, la precisión puede variar según el tipo de termopar y la aplicación.
5 Versatilidad: Existen varios tipos de termopares, como tipo K, tipo J, tipo T, etc., que están hechos de diferentes materiales, lo que les permite adaptarse a diferentes rangos de temperatura y aplicaciones específicas. Esto los hace versátiles y adecuados para una variedad de situaciones.
