### ISSUE TITLE
Ejercicio #1 F

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea3-grupo-1#6]
Responder: Mencione los tipos de sensores fotovoltaicos y defina 2.

**Comment by recursosssbb** [comment]
Ejercicio  1 - F ) **INFORMACION AMPLIADA EN PDF**


**Mencione los tipos de sensores fotovoltaicos y defina 2.**

Los sensores fotovoltaicos, también conocidos como células fotovoltaicas o células solares, son dispositivos que convierten la luz solar directamente en electricidad mediante el efecto fotovoltaico. Estos sensores son ampliamente utilizados en aplicaciones que van desde la generación de energía solar hasta la detección de luz en diversos dispositivos y sistemas. 

Describo varios tipos de sensores fotovoltaicos mas conocidos:

**Celulas fotovoltaicas de silicio monocristalino:**

Estas células están fabricadas a partir de lingotes de silicio monocristalino, lo que las hace altamente eficientes y con una alta pureza cristalina.
Son conocidas por su eficiencia y durabilidad, pero su fabricación puede ser costosa.
Se utilizan comúnmente en paneles solares para la generación de energía eléctrica.

**Celulas fotovoltaicas de silicio policristalino:**

Estas células se fabrican a partir de silicio policristalino, lo que las hace más grandes que las monocristalinas, aunque un poco menos eficientes.
A menudo se utilizan en paneles solares residenciales y comerciales debido a su relación costo-eficiencia.
