### ISSUE TITLE
Ejercicio #1 G

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea3-grupo-1#7]
Responder: ¿Qué es un sensor electroquímico?

**Comment by MariaBelen1** [comment]
Los sensores de gases electroquímicos se utilizan en aplicaciones industriales, médicas, automotrices y de otros tipos, para detectar y medir las concentraciones de una amplia gama de gases tóxicos, como el monóxido de carbono (CO) o el sulfuro de hidrógeno (H2S).
