### ISSUE TITLE
Ejercicio #2 H

### ISSUE THREAD

**Issue by joseorsili** [ISPC-TST-SENSORES-y-ACTUADORES-2023/tarea3-grupo-1#8]
Implemente una simulación (Mini Estación Metereológica) en Wokwi o
Proteus, utilizando ESP32 ó ARDUINO UNO con un sensor de temperatura, un
sensor de humedad y un sensor de presión atmosférica (barómetro – BMP180
ó BMP280) para tomar lecturas de los parámetros físicos del clima.

**Comment by ulisesaale** [comment]
Se arma estructura de componentes para la implementación de una Mini Estación Metereológica

1_Simulacion/P001_MiniEstacionMetereologica.pdsprj

Ejercicio #2 H #8 #

**Comment by Maxg8704** [comment]
Agrego ejemplo de codigo de simulacion de resultados para 1_Simulacion/P001_MiniEstacionMetereologica.pdsprj en proteus en carpeta 1_Proyecto
